#Defines the name of the workflow that will show in the github action
name: PHP Composer

#The event that will trigger the workflow, in this case it will be on push and pull request to main and staging
on:
  pull_request:
    branches: [ "main", "staging" ]

#The jobs that will run on this workflow
jobs:
#The name of the given job
  build-test:
  #Operating system enviroment the job will run on
    runs-on: ubuntu-latest
    #What the job should do
    steps:
    #Checks out the code form the repository such that the workflow can acces it
      # - uses: actions/checkout@v3
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix-build

      # Install MariaDB and set up the environment
      - name: Install MariaDB
        run: |
          sudo apt-get update
          sudo apt-get install -y mariadb-server
          sudo service mysql start

      # Configure MariaDB
      - name: Setup MariaDB
        run: |
          sudo mysql -e "CREATE DATABASE moodle;"
          sudo mysql -e "CREATE USER 'root'@'localhost' IDENTIFIED BY 'root';"
          sudo mysql -e "GRANT ALL PRIVILEGES ON moodle.* TO 'root'@'localhost';"
          sudo mysql -e "FLUSH PRIVILEGES;"
          sudo mysql -u root -proot moodle < $GITHUB_WORKSPACE/MoodleSQL.sql


      - name: Stop any existing MySQL/MariaDB
        run: |
          sudo service mysql stop || true
          sudo service mariadb stop || true

          
      - name: Run bash script
      #Runs this command to execute the test cases.
        run: sh .github/workflows/install_script.sh
