#Defines the name of the workflow that will show in the github action
name: PHP Composer

#The event that will trigger the workflow, in this case it will be on push and pull request to main and staging
on:
  pull_request:
    branches: [ "main", "staging" ]

#The jobs that will run on this workflow
jobs:
#The name of the given job
  build-test:
  #Operating system enviroment the job will run on
    runs-on: ubuntu-latest
    #What the job should do
    steps:
    #Checks out the code form the repository such that the workflow can acces it
      # - uses: actions/checkout@v3
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix-build

      # Install MariaDB
      - name: Install MariaDB
        run: |
          sudo apt-get update
          sudo apt-get install -y mariadb-server mariadb-client

      # Start MariaDB and adjust configuration
      - name: Configure MariaDB
        run: |
          sudo service mysql start
          
          # Update my.ini configuration (replace the following with valid config settings)
          sudo tee /etc/mysql/mariadb.conf.d/50-server.cnf <<EOF
          [mysqld]
          datadir=/var/lib/mysql
          port=3306
          innodb_buffer_pool_size=8182M
          skip-networking=0
          skip-bind-address
          EOF
          
          # Restart MariaDB to apply new configuration
          sudo service mysql restart
          
      - name: Run bash script
      #Runs this command to execute the test cases.
        run: sh .github/workflows/install_script.sh
