name: PHP Composer

on:
  pull_request:
    branches: [ "main", "staging" ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix-build

      - name: Install MariaDB
        run: |
          sudo apt-get update
          sudo apt-get install -y mariadb-server
          sudo mkdir -p /run/mysqld
          sudo chown -R mysql:mysql /run/mysqld
          sudo service mysql start

      - name: Setup MariaDB
        run: |
          sudo mysql -u root -proot -e "CREATE DATABASE IF NOT EXISTS moodle;"
          sudo mysql -u root -proot -e "GRANT ALL PRIVILEGES ON moodle.* TO 'root'@'localhost' IDENTIFIED BY 'root';"
          sudo mysql -u root -proot -e "FLUSH PRIVILEGES;"
          sudo mysql -u root -proot moodle < $GITHUB_WORKSPACE/MoodleSQL.sql

      - name: Stop any existing MySQL/MariaDB
        run: |
          sudo service mysql stop || true
          sudo service mariadb stop || true

      - name: Run bash script
        run: sh .github/workflows/install_script.sh
